<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery/jquery-1.8.1.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery/jquery.validate.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery/messages_cn.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-easyui-1.4.3/jquery.easyui.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-easyui-1.4.3/locale/easyui-lang-zh_CN.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/validate.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/extEasyUI.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/uploadPreview.js"></script>

<link rel="stylesheet" href="<%=request.getContextPath()%>/js/jquery-easyui-1.4.3/themes/default/easyui.css" type="text/css"/>
<link rel="stylesheet" href="<%=request.getContextPath()%>/js/jquery-easyui-1.4.3/themes/icon.css" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/css/index.css">     
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/css/demo.css">     
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery/extend_validate.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-easyui-1.4.3/datagrid-filter.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery/jquery-extensions.js"></script>